version: '3.8'

services:
  rag_api:
    build:
      context: .
      dockerfile: Dockerfile.lite
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
    env_file:
      - .env

volumes:
  pgdata2:
